# Copyright 2024 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: 'Octo STS'
description: |
  This action exchanges the workflow's identity token for a Github App token
  from the Octo STS service, in accordance with the trust policy of the target
  organization or repository.

inputs:
  domain:
    description: |
      The domain of the Octo STS instance to use to federate.
    default: octo-sts.dev

  scope:
    description: |
      The org/repo of the repository to which to request access.
    required: true

  identity:
    description: |
      The name of the trust policy to load from the target repository. The trust policy
      is loaded from https://github.com/{scope} from the file
      .github/chainguard/{identity}.sts.yaml
    required: true

  revoke:
    description: |
      Revoke the token in post job. Defaults to true. Useful to set to false, when required to pass the token between jobs.
      Use revoke action to revoke the token, after all jobs finished using it.
    required: true
    default: true

outputs:
  token:
    description: |
      The federated token to use for authentication.
    value: ${{ steps.octo-sts.outputs.token }}

runs:
  using: 'node20'
  main: 'index.js'
  post: 'post.js'
